# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "082955c7f94de3a19b269a13c08a329b"
name = "combo-bundles"
application_url = "https://shopify.platinuminfo.tech"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, write_metaobjects, write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://shopify.platinuminfo.tech/auth/callback",
  "https://shopify.platinuminfo.tech/auth/shopify/callback",
  "https://shopify.platinuminfo.tech/api/auth/callback"
]
[build]
automatically_update_urls_on_dev = true
